services:
  db:
    image: postgres:17
    container_name: smartrestaurant-db

    environment:
      POSTGRES_DB: smartrestaurant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
  