services:
  db:
    image: postgres:17
    container_name: smartrestaurant-db

    environment:
      POSTGRES_DB: smartrestaurant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    build:
      context: ./my-app/src/Backend/SmartRestaurant.Api
      dockerfile: Dockerfile
    container_name: smartrestaurant-api

    depends_on:
      - db

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__SmartRestaurant: "Host=db;Port=5432;Database=smartrestaurant;Username=postgres;Password=postgres"

    ports:
      - "5027:8080"

volumes:
  postgres_data:
